import { createActions } from 'redux-actions'

export default createActions(
  {},
  'START_REVIEWER',
  'REVIEW_CREATED',
  'REVIEW_REVIEWER_ADDED',
  'REVIEW_REVIEWER_REMOVED',
  'REVIEW_REVIEWER_UPDATED',
  'REVIEW_CUSTOM_FIELDS_SET',
  'REVIEW_CUSTOM_VALUE_SET',
  'REVIEW_FILE_ADDED',
  'REVIEW_FILE_REMOVED',

  'REVIEW_CONNECTED',
  'REVIEW_CONNECT_FAIL',

  'REVIEW_RESPONSE_FILE',
  'REVIEW_COMMENTS_RECEIVED',
  'REVIEW_COMMENT_ADDED',
  'REVIEW_COMMENT_REMOVED',
  'REVIEW_FILE_REQUEST',
  'REVIEW_COMMENT_ADD_REQUEST',
  'REVIEW_COMMENT_UPDATE_REQUEST',
  'REVIEW_COMMENT_REMOVE_REQUEST',
)
