import { createActions } from 'redux-actions'

export default createActions(
  'START_REVIEWER',
  'START_REVIEWEE',
  'REVIEW_CREATED',
  'REVIEW_INITIALIZED',

  'REVIEW_REVIEWER_ADD_REQUEST',
  'REVIEW_REVIEWER_ADDED',
  'REVIEW_REVIEWER_REMOVE_REQUEST',
  'REVIEW_REVIEWER_REMOVED',
  'REVIEW_REVIEWER_UPDATE_REQUEST',
  'REVIEW_REVIEWER_UPDATED',

  'REVIEW_CUSTOM_FIELDS_SET',
  'REVIEW_CUSTOM_VALUE_SET',

  'REVIEW_FILE_ADDED',
  'REVIEW_FILE_REMOVED',

  'REVIEW_JOIN_REQUEST',
  'REVIEW_CONNECTED',
  'REVIEW_CONNECT_FAIL',
  'REVIEW_INFO_RESPONSE',

  'REVIEW_COMMENTS_PROPAGATED',
  'REVIEW_COMMENT_ADDED',
  'REVIEW_COMMENT_REMOVED',
  'REVIEW_COMMENT_UPDATED',
  'REVIEW_COMMENT_MOVED',

  'REVIEW_FILE_REQUEST',
  'REVIEW_FILE_RESPONSE',

  'REVIEW_COMMENT_ADD_REQUEST',
  'REVIEW_COMMENT_UPDATE_REQUEST',
  'REVIEW_COMMENT_REMOVE_REQUEST',
  'REVIEW_COMMENT_MOVE_REQUEST',
)
